version: "1"
services:
  client:
    build: ./client
    container_name: next-ui
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - server
    networks:
      - projectgenie
  server:
    build: .
    container_name: node-api
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    networks:
      - projectgenie
  mongo:
    image: mongo
    container_name: mongo-db
    expose:
      - 27017
    ports:
      - "27017:27017"
    networks:
      - projectgenie
networks:
  projectgenie:
    driver: bridge
